
let livePlaying=false,pending=Promise.resolve(),generation=0;slider.style.display='none';
const controls=document.createElement('div');controls.innerHTML='<label><input id="manual" type="checkbox"> Manual joint velocities</label> '+['Slew','Boom','Stick','Bucket'].map((name,i)=>`<label>${name} <input class="joint" type="range" min="-1" max="1" step="0.05" value="0" aria-label="${name} velocity"></label>`).join(' ');document.querySelector('nav').after(controls);
async function request(path,body){let response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let result=await response.json();if(!response.ok)throw Error(result.error);frames[0]=result.frame;episode.shapes=result.shapes;index=0;draw();}
function advance(){let values=document.getElementById('manual').checked?Array.from(document.querySelectorAll('.joint')).map(x=>+x.value):null;pending=pending.then(()=>request('/step',{commands:values})).catch(e=>{livePlaying=false;generation++;document.getElementById('play').textContent='Play';document.getElementById('stats').textContent=e.message+' - reset required';});return pending;}
async function loop(token){while(livePlaying&&token===generation)await advance();}
document.getElementById('play').onclick=()=>{livePlaying=!livePlaying;document.getElementById('play').textContent=livePlaying?'Pause':'Play';generation++;if(livePlaying)loop(generation);};document.getElementById('step').onclick=()=>{livePlaying=false;generation++;document.getElementById('play').textContent='Play';advance();};document.getElementById('reset').onclick=()=>{livePlaying=false;generation++;document.getElementById('play').textContent='Play';pending=pending.then(()=>request('/reset',{seed:0})).catch(e=>document.getElementById('stats').textContent=e.message);};

const stopButton=document.createElement('button');stopButton.textContent='Stop session';document.querySelector('nav').append(stopButton);stopButton.onclick=async()=>{livePlaying=false;generation++;await pending;await fetch('/shutdown',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});document.getElementById('stats').textContent='Session stopped. Recorded episodes are preserved.';};
